######################################################################
# Automatically generated by qmake (2.01a) Mo Apr 14 20:29:08 2008
######################################################################

TEMPLATE = app
TARGET = 
CONFIG *= qt 
#CONFIG -= app_bundle
QT *= gui opengl
DEPENDPATH += .
INCLUDEPATH += .

MOC_DIR = .moc
!win:OBJ_DIR = .obj

# Input
HEADERS += ldraw.h ldrawrenderer.h matrix.h vector.h
SOURCES += ldraw.cpp main.cpp ldrawrenderer.cpp matrix.cpp vector.cpp
