// Copyright (C) 2004-2023 Robert Griebl
// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include <QWidget>

QT_FORWARD_DECLARE_CLASS(QQuickView)
QT_FORWARD_DECLARE_CLASS(QQmlEngine)

namespace Scanner {
class CameraPreview; // generated by qmltc
}

class CameraPreviewWidget : public QWidget
{
    Q_OBJECT
public:
    CameraPreviewWidget(QQmlEngine *engine, QWidget *parent = nullptr);
    ~CameraPreviewWidget() override;

    bool isActive() const;
    void setActive(bool newActive);

    QObject *videoOutput() const;

    Q_SIGNAL void clicked();

private:
    QQuickView *m_window = nullptr;
    QWidget *m_widget = nullptr;
    Scanner::CameraPreview *m_cameraPreview = nullptr;
};
