# Copyright (C) 2004-2026 Robert Griebl
# SPDX-License-Identifier: GPL-3.0-only

# Provides the imagescale target and IMAGESCALE_EXECUTABLE for the icon generators.
#
# The counterpart is RunImageScale.cmake, included by the generator scripts. None
# of this can be shared with them: they run under `cmake -P`, where neither
# add_subdirectory nor ExternalProject_Add is scriptable. Folding the two together
# would need a CMAKE_SCRIPT_MODE_FILE guard that stays correct forever, because
# CMAKE_CROSSCOMPILING is empty in script mode - without the guard the host branch
# below is taken silently on every generator run, cross build or not.
#
# Whatever runs it has to have Qt's bin directory in PATH: the tool is built well
# away from it, and qt-cmake does not put it there.
#
# The icons are generated by the machine running the build, so in a cross build
# imagescale cannot be part of this build - it would come out as an Android or
# iOS binary. Qt's own tools sidestep this by being imported from QT_HOST_PATH:
# qt_internal_add_tool() looks for a Qt6<Module>Tools package there and errors
# out on anything it cannot find, so it is of no use for a tool that only exists
# in this repository. Building it as a separate project against the host Qt is.

include_guard(GLOBAL)

set(IMAGESCALE_DIR "${CMAKE_BINARY_DIR}/tools")
set(IMAGESCALE_BUILD_DIR "${CMAKE_BINARY_DIR}/tools/imagescale-build")
set(IMAGESCALE_SOURCE_DIR "${CMAKE_SOURCE_DIR}/tools/imagescale")

if (CMAKE_CROSSCOMPILING)
    if (NOT QT_HOST_PATH)
        message(FATAL_ERROR "QT_HOST_PATH is required to build the imagescale tool")
    endif()

    set(IMAGESCALE_SUFFIX "")
    if (CMAKE_HOST_WIN32)
        set(IMAGESCALE_SUFFIX ".exe")
    endif()
    set(IMAGESCALE_EXECUTABLE "${IMAGESCALE_DIR}/imagescale${IMAGESCALE_SUFFIX}")

    # ExternalProject creates this in a step of its own, which is stamped as done
    # once and never repeated - so deleting the build directory by hand leaves the
    # configure step cd'ing into nothing. Recreating it here makes a plain re-run
    # of cmake enough to recover.
    file(MAKE_DIRECTORY "${IMAGESCALE_BUILD_DIR}")

    include(ExternalProject)
    ExternalProject_Add(imagescale
        SOURCE_DIR "${IMAGESCALE_SOURCE_DIR}"
        BINARY_DIR "${IMAGESCALE_BUILD_DIR}"
        BUILD_BYPRODUCTS "${IMAGESCALE_EXECUTABLE}"
        # an initial cache, not -D arguments: the per-configuration variables are
        # only used by the multi-config generators, and -D would warn about the
        # unused ones on every configure
        CMAKE_CACHE_ARGS
            "-DCMAKE_PREFIX_PATH:STRING=${QT_HOST_PATH}"
            "-DCMAKE_BUILD_TYPE:STRING=Release"
            # pin the output location, whatever generator and configuration the
            # parent build handed down
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY:PATH=${IMAGESCALE_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG:PATH=${IMAGESCALE_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE:PATH=${IMAGESCALE_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO:PATH=${IMAGESCALE_DIR}"
            "-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL:PATH=${IMAGESCALE_DIR}"
        INSTALL_COMMAND ""
        EXCLUDE_FROM_ALL TRUE
    )
else()
    add_subdirectory("${IMAGESCALE_SOURCE_DIR}" "${IMAGESCALE_BUILD_DIR}" EXCLUDE_FROM_ALL)
    set_target_properties(imagescale PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${IMAGESCALE_DIR}")
    set(IMAGESCALE_EXECUTABLE "$<TARGET_FILE:imagescale>")
endif()
